services:
  db:
    image: postgres:17  # Use the latest stable version
    container_name: rc_postgres_db
    environment:
      POSTGRES_USER: rc-admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    volumes:
      - ./schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: